- .gitignore
- libsystemd-sys/src/bus/mod.rs
- libsystemd-sys/src/bus/vtable.rs
- libsystemd-sys/src/daemon.rs
- libsystemd-sys/src/event.rs
- libsystemd-sys/src/id128.rs
- libsystemd-sys/src/lib.rs
- src/bus/mod.rs
- src/bus/types.rs
- src/daemon.rs
- src/id128.rs
- src/journal.rs
- src/lib.rs
Some commented code wasn't automatically fixed, handle that manually.  Also
move some comments for functions directly onto the function so gets into the
generated html.
I'm looking to make some cleanup changes and extend the library (especially around the journal, which I'm looking to use in a project).  Is there any roadmap?  Or any conventions that one should follow?  I figured I get this landed first so people using rustfmt have a place to start without making huge changes.
> Run rustfmt + fix long line length

- src/journal.rs
- tests/journal.rs
This PR adds seeking capability to Journal, supporting multiple positioning specifiers (head, current, tail, cursor, monotonic-clock, realtime-clock). It also enhances rustdoc for the whole module.
In order to let the test pass, this also fixes message kv-splitting.
This conflicts with #6.
> journal: implement seeking

- libsystemd-sys/src/lib.rs
- src/lib.rs
- src/login.rs
- tests/login.rs
This commit export the `login` module in `libsystemd-sys`
and additionally introduces a new `login` module with
initial support for retrieving system/user unit information.
> login: add support to retrieve unit identifier 

- src/journal.rs
- tests/journal.rs
This commit introduces support for filtering journal entries.
To filter results while iterating a Journal, it is now possible
to add filtering terms, AND/OR-ing them in predicates as well as
resetting back to an unfiltered iterator.
> journal: add support for match filters

- src/login.rs
- tests/login.rs
This PR introduces wrappers for some more getters from `sd-login`, namely:
* `get_slice()`
* `get_cgroup()`
* `get_machine_name()`
with meaningful testing (as far as possible).
I also spotted a couple of typos in my previous PR, which are fixed here "en passant".
> login: wrap some more getters

- src/journal.rs
- tests/journal.rs
This ensures that cursor strings passed to sd-journal FFI are valid
NUL-terminated C string.
Fixes #20
> journal: use CString for FFI cursor strings

- src/journal.rs
This Pull Request adds a new function `previous_record` to `systemd::journal::Journal`, which returns the previous journal entry. Its mostly identical to `next_record` (therefor I moved most ob `next_record` to ´get_record`)
> Added previous_record, modified next_record

- src/login.rs
- tests/login.rs
Introduce bindings for `sd_pid_get_session()` as well as `sd_pid_get_owner_uid()` from the native systemd.
Also add corresponding tests.
> login: introduce bindings for sd_pid_get_{session,owner_uid}()

- libsystemd-sys/src/journal.rs
- src/journal.rs
Also includes a convenience function to consume all records starting from
the cursor position.
> RFC: Implement waiting for recs using sd_journal_wait

- src/login.rs
Noticed this minor inconsistency and decided to fix it. Should be a no-op, uid_t and pid_t should be the same size so nothing was actually broken by this inconsistency.
> login: fix result type on get_owner_uid

- src/daemon.rs
Thanks for the quick turn-around on the uid_t fix, now for a slightly trickier issue. Happy to write tests / do whatever testing is appropriate, but this is working locally for me.
Previously `p.into_cstr()` was used inside a match arm to create an owned cstr which then went out of scope and was dropped before being used later in the ffi call. The borrow checker misses this because the escape from the variable lifetime is done through a raw pointer the checker does not track.
This change creates the owned string in the same scope as it is used so the raw pointer can be obtained and used without issue.
I'm not super happy about using map into an Option to do this, but it was the cleanest way I could think of with my limited Rust knowledge.
Thanks in advance!
> daemon: fix lifetime for pointer passed to ffi::sd_is_socket_unix

- Cargo.toml
Updates from 0.x to 0.y can be breaking changes. Require manual review
before accepting newer minor version bumps.
---
#39 except applicable to `master`.
> cargo: be stricter with dependency versions

- README.md
---
Using `0.*` only works if `rust-systemd` is never going to break API for the 0 series. If that's the case, then maybe a 1.x is in store? ;)
> readme: recommend depending via ~0.2

- Cargo.toml
Updates from 0.x to 0.y can be breaking changes. Require manual review
before accepting newer minor version bumps.
---
This would be nice to have to fix 0.1.0.
Fixes #44
> cargo: be stricter with dependency versions (for 0.1.1)

- Cargo.toml
- src/journal.rs
- src/lib.rs
- src/login.rs
* `mbox` does not build on nightly at the moment.  This PR gets rid of mbox as a dependency.
* In the previous code, if any of the string pointers returned by ffi were null, this would cause unsafe memory corruption since mbox never checks if the pointer is null.  With this PR, it's a safe panic instead.
* Most of these strings, like machine name for instance, probably don't have any guarantees that they're encoded in UTF8.  Rather than completely failing outright, it's usually recommended to replace invalid unicode characters with the unicode replacement characters and continue.  This is what `from_utf8_lossy` does.
> No more mbox.  Safer code.  Don't error on improper UTF8.

- src/journal.rs
This is a rebase of @bvinc 's PR so that bors runs. I'm planning on merging this for now (even though further work on the API is needed), as noded in #47
> Fix memory unsafety in the case of invalid UTF8 journal entries

- src/journal.rs
See: https://github.com/systemd/systemd/blob/878f2dae77e61ee6765b72318f49f8226f45ec0f/src/journal/sd-journal.c#L1192-L1215
`SD_JOURNAL_SYSTEM` filters on `system*`, and `SD_JOURNAL_CURRENT_USER` on `user-{uid}*`, but no flags selects *all* files.
> Fix docs for JournalFiles::All

- src/id128.rs
- src/journal.rs
- tests/journal.rs
See individual commit messages for details, the primary one being the second commit:
This function is not only useful for the timestamp itself, but also for
retrieving the boot ID of the current journal entry. IIUC, this is *not*
equivalent to the `_BOOT_ID` entry field, which may not be matched
properly in some cases. For more details, see:
systemd/systemd@dc00966
Implementation-wise, there's nothing surprising here. It's a
straightforward wrapper of the underlying API.  Also implement
`From<ffi::id128::sd_id128_t>` for `Id128` to convert to the wrapper
type from the ffi type and `PartialEq` to help testing (but which I also
need for my use case).
> journal: add monotonic_timestamp() and other fixes

- src/id128.rs
- src/journal.rs
- src/lib.rs
This introduces a default null-ID constructor for Id128 (similar to
`SD_ID128_NULL`) and removes a few unsafe uninitialized initializations.
> id128: add a default null constructor

- src/id128.rs
- src/journal.rs
Let me know if this isn't interesting -- I ran into a case where it'd be nice to include `JournalSeek` as a `Debug` rather than a `Display`. For `Id128`, it rarely makes sense to have `Display` but not `Debug`! :)
> Implement `Debug` for Id128, derive `Clone` and `Debug` for `JournalSeek`

- tests/daemon.rs
Use `slice::iter` instead of `into_iter` to avoid future breakage
`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.
> Use `slice::iter` instead of `into_iter` to avoid future breakage

- libsystemd-sys/build.rs
I ran into this when I defined the env var wrongly at the first try,
and then wondered why none of my changes seemed to have an effect.
> Rerun build.rs if non-pkg_config env var changes

- Cargo.lock
- Cargo.toml
- libsystemd-sys/Cargo.toml
- libsystemd-sys/build.rs
- libsystemd-sys/src/daemon.rs
- libsystemd-sys/src/lib.rs
- src/daemon.rs
- src/id128.rs
- src/journal.rs
- src/lib.rs
- tests/journal.rs
This is PR #97 from @kchibisov with additional commits to fix up various build/link issues.
I have not tested this with elogind, but it works fine with systemd.
Original PR message:
libelogind exposes identical interface to libsystemd, except some minor
parts like journal (it just has stubs for them afaisc).
Since libelogind has subset of libsystemd APIs, and since their C API is identical, I guess it makes sense to have support for it in this crate. Doing so will naturally bring support for elogind based systems for downstream projects like https://github.com/smithay/smithay and so they can launch on them just by activating a feature flag without changing their code, unless they are using journal API.
This was tested on elogind based system in smithay and worked fine. I' not sure if docs …
> Add elogind support

- Cargo.toml
- README.md
- libsystemd-sys/Cargo.toml
- libsystemd-sys/build.rs
- libsystemd-sys/src/bus/vtable.rs
- libsystemd-sys/src/daemon.rs
- libsystemd-sys/src/lib.rs
- src/daemon.rs
- src/lib.rs
For features to work right, they need to be adative. IOW: enabling
features can only _extend_ the API.
elogind does not support the journal apis, so instead provide that as a
feature.
Also, remove the elogind behavior from the build.rs script and document
the use of environment variables to control the build instead.
In the future, we could consider having our build.rs try to link with
elogind when systemd is absent (and features permit it?).
> make features adative (remove elogind, add journal)

- .travis.yml
- travis builds for stable, beta, and nightly
- nightly sometimes doesn't have a rustfmt component
- we already only run rustfmt (`cargo fmt`) in github actions (fmt.yml)
- avoid installing it at all on travis
> ci: remove rustfmt from travis, rely on gha

- Cargo.lock
- Cargo.toml
- README.md
- libsystemd-sys/src/bus/vtable.rs
- libsystemd-sys/src/id128.rs
- src/id128.rs
- src/journal.rs
- tests/journal.rs
- removes our juggling with iteration around seeking. user is now
required to iterate themselves
- adds direct access to the fields of a journal entry rather than only
having them in the mixed iteration/allocate btreemap functions
(next_entry, etc)
- Drops `Current` as a seek location, it's a noop that exists to call
`sd_journal_next()` in a roundabout way that no longer makes sense
- remove journal seeking from the journal opening. all our tests
already explicitly seek. I expect everything else is likely to do
this as well. It also makes our interface more direct
Fixes #31, Fixes #91
> journal: expose more direct interface

- examples/journal-reader.rs
- src/journal.rs
The existing interfaces don't quite work right. Give folks access to the
actual systemd interface.
Also add an example of using the low-level journal interfaces to stream data.
> journal: make wait() public 

- .github/workflows/ci.yml
- bors.toml
- src/bus/mod.rs
- src/bus/types.rs
- src/journal.rs
This does add a few directed suppressions around
`clippy::should_implement_trait`. We have functions named `next()` on a
few of our types. These can't quite be translated to `Iterator` impls.
Seems like it could make sense to rename them.
> fix all clippy warnings and check in ci

- src/daemon.rs
- src/login.rs
Without this, rustc 1.48 (as of now, rustc nightly-2020-10-04) is
expected to fail to build rust-systemd.
Rustc issue: https://github.com/rust-lang/rust/issues/77586
> use :: to disambiguate `use`

- src/journal.rs
Implement AsRawFd for JournalRef as it is for BusRef.
The immediate use case is to allow asynchronous polling for events
> Implement AsRawFd for JournalRef

- .github/workflows/ci.yml
- libsystemd-sys/build.rs
Without this, systems lacking libsystemd result in annoying link errors.
> libsystemd-sys/build: actually bail out if pkg-config fails and env overrides are not used

- libsystemd-sys/build.rs
> libsystemd-sys: fix cargo directive for library to link

- .github/workflows/check.yml
- .github/workflows/features.yml
- Cargo.toml
- README.md
- libsystemd-sys/Cargo.toml
All code included in rust-systemd that was not relicensed by the
contributors has either been removed, or corresponds to
non-copyrightable elements (direct translation of C api definitions into
rust).
The new code was written without reference to the removed code
Closes #92 and closes #127
Thanks everyone for your help on this!
> license: add GCC-exception-2.0

- src/bus/mod.rs
```
warning: explicit lifetimes given in parameter types where they could be elided (or replaced with `'_` if needed by type declaration)
--> src/bus/mod.rs:1821:5
|
1821 |     pub fn iter<'a>(&'a mut self) -> crate::Result<MessageIter<'a>> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `#[warn(clippy::needless_lifetimes)]` on by default
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
warning: 1 warning emitted
```
> remove explicit lifetime so clippy is happy

- examples/socket-activation.rs
- src/daemon.rs
- tests/daemon.rs
The documentation and the type of dameon::listen_fds didn't seem to
match.  The type is Fd, but it is used as an integer.  While this isn't
technically a problem, it's a little confusing to read.  This is my
attempt to provide something more useful, and perhaps easier to use
correctly.
This adds two structs: ListenFds and ListenFdsRange.  The first is
returned by listen_fds if assuming there isn't an error.  The second is
returned by the first's iter() method.  This allow for a way to access
multiple file descriptors if they happen to be returned.
> Return custom struct, iterable struct from sd_listen_fds

- libsystemd-sys/src/journal.rs
- libsystemd-sys/src/lib.rs
- src/journal.rs
This started out as a way of trying to reduce the number of allocations
made by the log_record function.  It was making allocations during:
1. The construction of each of the strings.
2. The initial construction of the vector
3. Potentially one or two more for the subsequent push calls
4. The construction of the AsRef vector
5. The construction of the const_iovec in the array_to_iovecs function
This reduces it to:
1. The construction of each of the strings.
2. The construction of the vector of const_iovec
However, as a result of looking at these interfaces, I noticed a couple
of things.  First was that the libsystemd-sys crate was defining an
iovec struct that's a duplicate of the libc::iovec struct.  I removed
this and just pub-defined the libc version.
The second is that array_to_iovecs …
> Update journal logging interface

- Cargo.lock
- Cargo.toml
- src/id128.rs
Something I've added locally (`#[serde(with = "")]`), thought it could be useful to others
> Add serialization support to Id128

- Cargo.toml
- libsystemd-sys/Cargo.toml
- libsystemd-sys/src/journal.rs
- src/journal.rs
The method `sd_journal_open_namespace` was added in systemd v245 (see the [systemd changelog](https://github.com/systemd/systemd/blob/v245/NEWS#L79-L86)). This version is not yet available in the stable branches of some major Linux distributions, for instance in Debian 10 which contains version 241 (https://packages.debian.org/buster/libsystemd-dev).
This pull request adds the feature flag `systemd_v245`. `sd_journal_open_namespace` is only available if this feature flag is set.
This is the first step to fix issue #132.
> Add feature flag for systemd version 245

- examples/journal-reader.rs
If next if called directly after seek tail, a random old entry is pointed.
See the implementation in journalctl:
https://github.com/systemd/systemd/blob/8389fd19d20370077f2d5601af0a089ec92ece05/src/journal/journalctl.c#L1292-L1299
And this related bug report: https://bugs.freedesktop.org/show_bug.cgi?id=64614
> Fix journal-reader example to point to the most recent entry

- tests/login.rs
The assertion in `test_get_unit` failed on the assumption that there could only be either a system unit or a user unit, while having both is possible.
For example, in my system every desktop application gets its own user unit (e.g. `app-org.kde.konsole-<SOMEID>.scope`) and this is in turn part of the system unit which owns the user session (e.g. `user@1000.service`).
I'm assuming that every user unit will be part of such a `user@.service` and so I changed the assertion to only verify that condition.
> Fix running tests inside user units

- tests/journal.rs
In order to create a cursor, the journal must be at a valid entry. As the docs say:
Note that sd_journal_get_cursor() will not work before
sd_journal_next(3) (or related call) has been called at least
once, in order to position the read pointer at a valid entry.
The existing tests do this, but at least on recent versions of systemd (255), it seems that calling sd_journal_next after a seek to tail does not meet this requirement. If the journal is at the tail, subsequent nexts will always stay a the abstract 'tail' position, not at a valid entry because the "next" call will never seek backwards. This causes cursor creation to fail.
A similar issue exists in the 'match' test. It seeks to tail and then attempts to 'next' in a loop, but this will always be 'tail', so it never sees the matching …
> Fix journal cursor tests

- README.md
- src/lib.rs
- tests/readme.rs
> Merge #274

- src/journal.rs
- tests/journal.rs
Hello,
This is a great crate, but I need a function that I want to share.
I created the function pub fn timestamp_usec(&self) -> Result<u64> on JournalRef struct. It the same than the timestamp, but it gives a direct access to the realtime_usec u64 value. 
I also made a test to ensure that both functions "timestamp_usec" and "timestamp" return the same.
Thank you
PS 
Without this function I can still get the u64 value with the help of workarounds ;)
> New function timestamp_usec

- examples/enumerate_sessions.rs
- libsystemd-sys/src/login.rs
- src/login.rs
- tests/login.rs
Add safe Rust wrappers for systemd-logind session enumeration functions that were previously only available through unsafe FFI. These functions enable applications to query systemd for information about active sessions without needing to implement unsafe memory management.
Added Functions:
- `login::get_sessions()` - Returns a list of all active session IDs
- `login::get_session_uid(session)` - Get the user ID of a session
- `login::get_session_start_time(session)` - Get session start time as microseconds since Unix epoch
- `login::get_session_tty(session)` - Get TTY device name (returns `Option<String>`)
- `login::get_session_remote_host(session)` - Get remote host for SSH sessions (returns `Option<String>`)
- `login::get_session_display(session)` - Get display for GUI sessions (returns …
> Add rust wrappers for systemd-logind session functions
